@host = http://localhost:5080

GET {{host}}/api/products?page=1&pageSize=10

###

GET {{host}}/api/products/1

###

POST {{host}}/api/products
Content-Type: application/json

{
  "sku": "STL-010",
  "name": "Podkladka M8",
  "description": "Podkladka plaska",
  "quantity": 200,
  "unitPrice": 0.15,
  "supplierId": 1
}

###

POST {{host}}/api/products/1/issue
Content-Type: application/json

{
  "quantity": 10
}

###

GET {{host}}/api/suppliers
